# Generated by Django 5.1.3 on 2024-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsp', models.FloatField(help_text='Horas Solar Pico')),
                ('security_factor', models.FloatField(help_text='Factor de seguridad')),
                ('imprevistos', models.FloatField(help_text='Porcentaje para imprevistos')),
                ('material_electrico', models.FloatField(help_text='Costo de material eléctrico')),
                ('certificacion_retie', models.FloatField(help_text='Costo de certificación RETIE')),
            ],
            options={
                'verbose_name': 'Datos Externos',
                'verbose_name_plural': 'Datos Externos',
            },
        ),
        migrations.CreateModel(
            name='TipoTeja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_antes_de_iva', models.FloatField()),
                ('imagen', models.ImageField(upload_to='tejas/')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('km_desde_medellin', models.FloatField()),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Viaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_hospedaje', models.FloatField()),
                ('precio_viaticos', models.FloatField()),
            ],
            options={
                'verbose_name': 'Viáticos',
                'verbose_name_plural': 'Viáticos',
            },
        ),
    ]
