# Generated by Django 5.1.3 on 2024-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio_conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datosexternos',
            name='certificacion_retie',
        ),
        migrations.AddField(
            model_name='datosexternos',
            name='certificacion_retie_v1',
            field=models.FloatField(default=0, help_text='valor #1 para la operacion de certificación RETIE'),
        ),
        migrations.AddField(
            model_name='datosexternos',
            name='certificacion_retie_v2',
            field=models.FloatField(default=0, help_text='valor #2 para la operacion de certificación RETIE'),
        ),
    ]
