# Generated by Django 5.1.3 on 2024-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datosexternos_pct_instalacion_datosexternos_pct_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosexternos',
            name='consultoria_tributaria',
            field=models.FloatField(default=0.025, help_text='Porcentaje de consultoria tributaria'),
        ),
    ]
