# Generated by Django 5.1.3 on 2024-12-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datosexternos_consultoria_tributaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosexternos',
            name='proteccionCNO',
            field=models.FloatField(default=200000, help_text='Costo de protección CNO'),
        ),
    ]
