# Generated by Django 5.1.3 on 2024-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_datosexternos_proteccioncno'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio_conexion',
            name='since',
            field=models.FloatField(default=0, help_text='Desde'),
        ),
        migrations.AddField(
            model_name='estudio_conexion',
            name='until',
            field=models.FloatField(default=0, help_text='Hasta'),
        ),
    ]
