# Generated by Django 5.1.3 on 2024-12-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estudio_conexion_since_estudio_conexion_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosexternos',
            name='material_electrico',
        ),
        migrations.AddField(
            model_name='datosexternos',
            name='material_electrico_v1',
            field=models.FloatField(default=0, help_text='valor #1 para la operacion de material electrico'),
        ),
        migrations.AddField(
            model_name='datosexternos',
            name='material_electrico_v2',
            field=models.FloatField(default=0, help_text='valor #2 para la operacion de material electrico'),
        ),
    ]
