# Generated by Django 5.1.3 on 2024-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_datosexternos_material_electrico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosexternos',
            name='ipc',
            field=models.FloatField(default=0.13, help_text='Porcentaje de IPC'),
        ),
        migrations.AddField(
            model_name='datosexternos',
            name='valor_generacion',
            field=models.FloatField(default=348.02, help_text='Valor de generación de energia en bolsa'),
        ),
    ]
