# Generated by Django 5.1.3 on 2024-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datosexternos_ipc_datosexternos_valor_generacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosexternos',
            name='AOM_MWP_ANUAL',
            field=models.FloatField(default=45000000, help_text='AOM MWp/anual'),
        ),
        migrations.AddField(
            model_name='datosexternos',
            name='tarifa_impuesto_renta',
            field=models.FloatField(default=0.35, help_text='Tarifa de impuesto de renta'),
        ),
    ]
